# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:


#####
#
# Whitespace and general checks
#


- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: detect-private-key
  - id: fix-byte-order-marker
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: end-of-file-fixer
  - id: trailing-whitespace



#####
#
# License headers (all files)
#


- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: forbid-crlf
  - id: insert-license
    name: Insert license in terraform, yaml, sh, and python files
    files: \.(tf|py|yaml|sh)$
    args:
      - --license-filepath
      - docs/LICENSE_HEADER.txt
  - id: insert-license
    name: Insert license in go, and proto files
    files: \.(go|proto)$
    exclude: ".pb.go$"
    args:
      - --license-filepath
      - docs/LICENSE_HEADER.txt
      - --comment-style
      - //
  - id: insert-license
    name: Insert license Dockerfiles
    files: Dockerfile$
    args:
      - --license-filepath
      - docs/LICENSE_HEADER.txt
  - id: insert-license
    name: Insert license in sql files
    files: \.sql$
    args:
      - --license-filepath
      - docs/LICENSE_HEADER.txt
      - --comment-style
      - /*| *| */

#####
#
# Spellcheck
#

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
    - id: codespell
      files: \.(tf|py|yaml|sh|md)$

#####
#
# Python
#


# Lint and fix Python code
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      args:
        - --fix
    - id: ruff-format


#####
#
# Terraform
#

# Formatting and validation
- repo: https://github.com/AleksaC/terraform-py
  rev: v1.9.8
  hooks:
    - id: tf-fmt
    - id: tf-validate



#####
#
# Go code
#


# Compiling and unit testing
- repo: https://github.com/TekWizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
  - id: go-fmt
  - id: my-cmd
    name: "go-generate"
    args:
    - go
    - generate
    - examples/risk/loadtest/src/main.go
  - id: go-vet-mod
  - id: go-build-mod
  - id: go-test-mod

# Linting
- repo: https://github.com/golangci/golangci-lint
  rev: v1.61.0
  hooks:
  - id: golangci-lint-full
    args:
      - examples/risk/loadtest/src/...
      - examples/risk/agent/src/...
