# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- id: 'terraform init'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo ""
      echo "*************** TERRAFORM INIT ******************"
      echo "******* At environment: $PROJECT_ID ********"
      echo "*************************************************"
      terraform init || exit 1
- id: 'terraform plan'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo ""
      echo "*************** TERRAFORM PLAN ******************"
      echo "******* At environment: $PROJECT_ID ********"
      echo "*************************************************"
      terraform plan -out=plan.tfplan -var="project_id=$PROJECT_ID" || exit 1
- id: 'terraform apply'
  name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo ""
      echo "*************** TERRAFORM PLAN ******************"
      echo "******* At environment: $PROJECT_ID ********"
      echo "*************************************************"
      terraform apply plan.tfplan|| exit 1
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', '${_CLUSTER_NAME}', '--region=${_CLUSTER_REGION}', '--project=${PROJECT_ID}'] # Authenticate with GKE
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Apply Kueue Config'
  entrypoint: 'kubectl'
  args:
  - 'apply'
  - '-k'
  - 'kubernetes'
  - '--server-side'
substitutions:
      _CLUSTER_NAME: "gke-risk-research" # default value
      _CLUSTER_REGION: "us-central1" # default value
# options:
#       logging: CLOUD_LOGGING_ONLY
