name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v3
    - name: Install protoc
      uses: arduino/setup-protoc@v3
    - name: Run pre-commit 
      uses: pre-commit/action@v3.0.1
