name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install protoc
      uses: arduino/setup-protoc@v3
      with:
        version: '29.2'
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23'
    - name: Install protoc-gen-go
      run:  go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.33.0
    - name: Install protoc-gen-go-grpc
      run:  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
    - name: Install golangci-lint
      run:  go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
